from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist'
C=json.loads((ROOT/'site-config.json').read_text())
DOMAIN=C['domain'].rstrip('/')
NAME=C['name']
PHONE=C['phone']
TEL='tel:'+C['phoneE164']
WA='https://wa.me/'+C['whatsapp']+'?text=Merhaba%2C%20Diyarbak%C4%B1r%20%C3%A7ekici%20hizmeti%20i%C3%A7in%20bilgi%20almak%20istiyorum.'
PAGES=[]
def esc(s): return html.escape(s,quote=True)
def icon(n):
 paths={'phone':'M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.96.35 1.9.69 2.79a2 2 0 0 1-.45 2.11L8.09 9.89a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.89.34 1.83.57 2.79.69A2 2 0 0 1 22 16.92z','arrow':'M7 17 17 7M7 7h10v10','pin':'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0z M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0','chat':'M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5z','truck':'M1 3h14v13H1z M15 8h4l3 5v3h-7 M5 16a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M18 16a3 3 0 1 0 0 6 3 3 0 0 0 0-6'}
 return '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+paths[n]+'"/></svg>'
def buttons(): return f'<div class="actions"><a class="btn yellow" href="{TEL}">{icon("phone")} Hemen ara</a><a class="btn outline" href="{WA}" target="_blank" rel="noopener noreferrer">{icon("chat")} WhatsApp’tan yaz</a></div>'
NAV=[('','Ana Sayfa'),('hizmetler/','Hizmetler'),('hizmet-bolgeleri/','Hizmet Bölgeleri'),('kurumsal/','Kurumsal'),('blog/','Blog'),('iletisim/','İletişim')]
def header(path):
 nav=''.join(f'<a href="/{u}"'+(' aria-current="page"' if path==u else '')+f'>{t}</a>' for u,t in NAV)
 return f'<a class="skip" href="#main">İçeriğe geç</a><div class="topbar"><div class="wrap"><span>DİYARBAKIR MERKEZ & ÇEVRE İLÇELER</span><a href="{TEL}">Çekici talebi: {PHONE}</a></div></div><header class="header"><div class="wrap navwrap"><a class="brand" href="/" aria-label="{NAME} ana sayfa"><span class="brand-icon">{icon("truck")}</span><span>HİZMET <b>OTO ÇEKİCİ</b><small>DİYARBAKIR</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" type="button">Menü <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Ana menü">{nav}</nav><a class="navphone" href="{TEL}">{icon("phone")}<span>{PHONE}</span></a></div></header>'
def footer():
 return f'<footer><div class="wrap footgrid"><div><a class="brand" href="/"><span class="brand-icon">{icon("truck")}</span><span>HİZMET <b>OTO ÇEKİCİ</b><small>DİYARBAKIR</small></span></a><p>Diyarbakır’da oto çekici ve oto kurtarma.<br>Konumunuzu paylaşın, ihtiyacınızı birlikte netleştirelim.</p></div><div><h2>Sayfalar</h2>'+''.join(f'<a href="/{u}">{t}</a>' for u,t in NAV[1:])+f'</div><div><h2>Bize ulaşın</h2><a class="footerphone" href="{TEL}">{PHONE}</a><a href="{WA}" target="_blank" rel="noopener noreferrer">WhatsApp üzerinden iletişim</a><p>Diyarbakır merkez ve çevre ilçeler</p></div></div><div class="wrap legal"><span>© 2026 {NAME}</span><a href="/gizlilik/">Gizlilik</a></div></footer><div class="fixed-contact" aria-label="Hızlı iletişim"><a class="float-wa" href="{WA}" target="_blank" rel="noopener noreferrer">{icon("chat")}<span>WhatsApp</span></a><a class="float-call" href="{TEL}">{icon("phone")}<span>Hemen ara</span></a></div>'
def cta(): return '<section class="cta"><div class="wrap cta-row"><div><span class="eyebrow">BİR TELEFON KADAR YAKIN</span><h2>Çekici mi gerekiyor?<br>Konumunuzu paylaşın.</h2><p>Aracınızın durumu, varış noktası ve uygunluk için bizi arayın.</p></div>'+buttons()+'</div></section>'
def page(path,title,desc,body,crumb=None,article=False):
 url=DOMAIN+'/'+path
 schema=[{'@context':'https://schema.org','@type':'AutomotiveBusiness','@id':DOMAIN+'/#business','name':NAME,'url':DOMAIN+'/','telephone':C['phoneE164'],'areaServed':{'@type':'AdministrativeArea','name':'Diyarbakır'},'description':'Diyarbakır merkez ve çevre ilçelerinde oto çekici ve oto kurtarma hizmeti.'}]
 if path:
  schema.append({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Ana Sayfa','item':DOMAIN+'/'},{'@type':'ListItem','position':2,'name':crumb or title,'item':url}]})
 if article: schema.append({'@context':'https://schema.org','@type':'BlogPosting','headline':title,'description':desc,'mainEntityOfPage':url,'author':{'@type':'Organization','name':NAME},'publisher':{'@id':DOMAIN+'/#business'},'inLanguage':'tr-TR'})
 fulltitle=title if path=='' else title+' | Hizmet Oto Çekici'
 data=f'<!doctype html>\n<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(fulltitle)}</title><meta name="description" content="{esc(desc)}"><meta name="theme-color" content="#11191c"><link rel="canonical" href="{url}"><meta property="og:type" content="'+('article' if article else 'website')+f'"><meta property="og:locale" content="tr_TR"><meta property="og:title" content="{esc(fulltitle)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{url}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="/assets/site.js" defer></script></head><body>'+header(path)+'<main id="main">'+body+'</main>'+footer()+'</body></html>'
 dest=OUT/path/'index.html' if path else OUT/'index.html'
 dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(data)
 PAGES.append(path)
def intro(kicker,title,desc,path):
 return f'<section class="pagehero"><div class="wrap"><div class="breadcrumb"><a href="/">Ana Sayfa</a><span>/</span><span>{esc(kicker)}</span></div><span class="eyebrow">{esc(kicker.upper())}</span><h1>{title}</h1><p>{desc}</p></div></section>'
SERVICES=[
 ('diyarbakir-oto-cekici','Oto çekici','Aracınızı bulunduğu noktadan servise veya belirlediğiniz adrese taşıma talebi.','Aracınızın hareket edemediği anlarda, doğru taşıma planı konum ve araç bilgisiyle başlar. Diyarbakır merkez ve çevre ilçelerinde oto çekici ihtiyacınız için bizi arayabilirsiniz.', [('Çekici talebi nasıl oluşturulur?','Bulunduğunuz ilçeyi, mahalleyi ve yolun gidiş yönünü belirtin. Konum bağlantısı, aracın marka ve modeli ile birlikte paylaşıldığında talebin değerlendirilmesini kolaylaştırır. Aracın yürür durumda olup olmadığını ve götürülmesini istediğiniz adresi de söyleyin.'),('Araç bilgisi neden önemli?','Tekerleklerin dönmesi, direksiyonun hareketi, vitesin konumu ve aracın bulunduğu zeminin durumu taşıma yöntemini etkiler. Arızanın nedenini bilmiyorsanız tahminde bulunmanız gerekmez; gözlemlediğiniz durumu anlatmanız yeterlidir.'),('Ücret ve varış süresi','Taşıma mesafesi, araç tipi, yükleme koşulları ve ekip uygunluğu birlikte değerlendirilir. Hareket öncesinde toplam ücretin kapsamını ve tahmini ulaşım süresini telefonda netleştirin. Trafik veya yol koşullarına göre süre değişebilir.')]),
 ('diyarbakir-oto-kurtarma','Oto kurtarma','Hareket edemeyen veya erişimi zor bir noktada kalan araçlar için durum değerlendirmesi.','Her yolda kalma durumu standart bir taşıma değildir. Diyarbakır oto kurtarma taleplerinde aracın pozisyonu ve bulunduğu alan değerlendirilerek uygun ekipman ihtiyacı belirlenir.', [('Durumu önceden anlatın','Aracın yoldan çıkması, tekerleğin sıkışması veya yüklemeye uygun olmayan bir noktada kalması farklı bir hazırlık gerektirebilir. Konumla birlikte güvenli bir noktadan çekilmiş fotoğraf paylaşmak, alanın ve aracın durumunun anlaşılmasına yardımcı olur.'),('Ekipman uygunluğu','Araç türünü, yaklaşık ağırlığını biliyorsanız bu bilgiyi ve tekerleklerin durumunu paylaşın. Her kurtarma talebinin aynı araç veya ekipmanla karşılanabileceği varsayılmamalıdır. Hizmet uygunluğu görüşme sırasında teyit edilir.'),('Kurtarma ve taşıma birlikte planlanır','Aracın bulunduğu noktadan alınması ile sonrasında servise taşınması ayrı aşamalardır. Aracın götürüleceği yerin açık olması ve teslim alacak kişinin bilgisi taşıma planını kolaylaştırır. Talep öncesinde iki aşamanın ücret kapsamını da sorun.')]),
 ('diyarbakir-acil-cekici','Acil çekici talebi','Beklenmedik arıza ve yolda kalma durumlarında doğrudan telefonla iletişim.','Diyarbakır’da acil oto kurtarma veya çekici arıyorsanız konumunuzu ve araç durumunu telefonda paylaşın. Ekibin uygunluğu ve ulaşım tahmini görüşmede netleşir.', [('İlk görüşmede gerekli bilgiler','İlçe, yol veya cadde adı, gidiş yönü ve yakınınızdaki ayırt edici bir nokta ile başlayın. Ardından araç türünü ve neden hareket edemediğini anlatın. Telefonla konuştuğunuz numaranın ulaşılabilir kalması koordinasyonu kolaylaştırır.'),('Yakınlık kadar uygunluk da önemlidir','En yakın çekici araması yaparken yalnızca mesafeye bakmayın. Aracın alınacağı alana erişim ve gereken ekipmanın uygunluğu da belirleyicidir. Ulaşım süresini hizmet sağlayıcıyla doğrudan görüşün.'),('Talebi netleştirin','Aracın götürüleceği adresi mümkünse baştan belirtin. Yerinde müdahale ile çekici hizmeti aynı şey değildir; hangi işlemin istendiğini açıkça konuşun. Bu iletişim hattı oto çekici talepleri içindir; genel acil yardım hattı değildir.')]),
 ('diyarbakir-arac-tasima','Servise araç taşıma','Arızalı aracınızın seçtiğiniz servis veya teslim adresine taşınmasını planlama.','Diyarbakır’da aracınızı servise götürmek için çekiciye ihtiyaç duyduğunuzda, alınış ve teslim noktalarını birlikte planlayın.', [('Servis teslimini hazırlayın','Servisin açık olduğu saatleri ve aracınızı kabul edeceğini teyit edin. Teslim alacak kişinin adı ile telefonunu hazır bulundurun. Servis kapalıysa farklı bir teslim noktası için taşıma öncesinde anlaşın.'),('Alınış noktasını açıklayın','Araç kapalı otoparkta, dar sokakta veya eğimli bir alandaysa bunu önceden bildirin. Giriş yüksekliği ve manevra alanı taşıma aracının yaklaşmasını etkileyebilir. Erişim bilgisi eksik olduğunda talebin yerinde yeniden değerlendirilmesi gerekebilir.'),('Teslim bilgilerini netleştirin','Aracın anahtarının kimde olacağını, araçla kimin ilgileneceğini ve teslimde aranacak numarayı paylaşın. Araçtaki görünür durumun önceden konuşulması ve teslim noktasının açıkça belirlenmesi süreci daha anlaşılır kılar.')])]
def servicecards():
 return '<div class="servicegrid">'+''.join(f'<a class="servicecard" href="/hizmetler/{slug}/"><span class="cardnum">0{i+1}</span><span class="card-arrow">{icon("arrow")}</span><h3>{name}</h3><p>{desc}</p><span class="textlink">Hizmeti incele</span></a>' for i,(slug,name,desc,_,__) in enumerate(SERVICES))+'</div>'
DISTRICTS=[('kayapinar','Kayapınar','Apartman ve site otoparklarından araç alınırken giriş yüksekliği, otopark katı ve manevra alanı önemlidir. Kayapınar’da çekici talep ederken aracınızın açık alanda mı kapalı otoparkta mı olduğunu belirtin.','Site ve otoparktan araç alınması','Güvenlik noktasına ulaşım bilgisi ve aracın park ettiği bölüm önceden paylaşılabilir. Dar bir giriş varsa fotoğrafla göstermek, taşıma aracının erişiminin değerlendirilmesini kolaylaştırır.'),('baglar','Bağlar','Bağlar’da cadde üzerindeki arızalar veya mahalle içindeki araç taşıma ihtiyaçları için tam konum paylaşın. Aynı adı taşıyan işletmeler veya yakın sokaklar arasında karışıklığı azaltmak için harita işareti kullanın.','Mahalle içi ulaşımın planlanması','Aracın sokak içinde mi ana yol üzerinde mi olduğu, yaklaşma yönü ve çevrede park eden araçların yarattığı alan kısıtı önem taşır. Konumun yanında sokağın girişini tarif etmek koordinasyonu kolaylaştırır.'),('yenisehir','Yenişehir','Yenişehir’de iş yeri, konut veya cadde çevresinde kalan aracınız için çekici ihtiyacını telefonla iletebilirsiniz. Aracın bulunduğu tarafı ve götürüleceği servisi baştan belirtmek taşıma planını netleştirir.','Cadde üzerinden servise taşıma','Araç bölünmüş bir yoldaysa gidiş yönünü paylaşın. Servisin aracı kabul edeceğini ve teslim alacak kişiyi doğrulayın. Trafik koşullarına bağlı ulaşım tahmini görüşme sırasında değerlendirilir.'),('sur','Sur','Sur ilçesinde oto çekici talebi oluştururken aracın bulunduğu sokağı ve giriş koşullarını tarif edin. Dar geçişler veya araç erişiminin kısıtlı olduğu alanlarda taşıma yönteminin önceden değerlendirilmesi gerekir.','Dar sokaklarda erişim bilgisi','Araç çevresindeki alanı güvenli bir noktadan fotoğraflayarak paylaşabilirsiniz. Sokağın genişliği, dönüş alanı ve varsa giriş kısıtları ekipman seçimini etkiler. İlçe adına ek olarak mahalle ve konum bilgisi mutlaka iletilmelidir.')]
REGIONS=['Bismil','Çınar','Ergani','Silvan','Eğil','Dicle','Çermik','Çüngüş','Hani','Hazro','Kocaköy','Kulp','Lice']
def regionlinks():return '<div class="districtgrid">'+''.join(f'<a href="/hizmet-bolgeleri/{slug}-cekici/"><span><small>DİYARBAKIR</small>{name} çekici</span>{icon("arrow")}</a>' for slug,name,*_ in DISTRICTS)+'</div>'
ARTICLES=[
 ('diyarbakir-cekici-fiyatlari-nelere-gore-belirlenir','ÜCRET & PLANLAMA','Diyarbakır çekici fiyatları neye göre belirlenir?','Tek bir fiyat yerine, teklif alırken paylaşmanız gereken bilgileri öğrenin.',[
 ('Fiyat için yalnızca ilçe adı yeterli mi?','Diyarbakır’da çekici fiyatı sorarken yalnızca “Bağlar’dan araç alınacak” demek, taşımanın tamamını tarif etmez. Alınış noktası kadar aracın götürüleceği adres de önemlidir. Aynı ilçeden alınan iki aracın teslim mesafesi ve yükleme koşulları farklı olabilir. Bu nedenle net teklif için iki konumu birlikte paylaşın.'),
 ('Mesafe ve araç durumu','Aracın türü, boyutları ve hareket durumu taşıma hazırlığını etkiler. Tekerlekleri dönmeyen veya standart yüklemeye uygun olmayan bir araç, farklı ekipman gerektirebilir. Arızanın teknik adını bilmiyorsanız motorun çalışıp çalışmadığını, aracın hareket edip etmediğini ve bulunduğu zemini anlatın. Fotoğraf, anlatımı destekleyebilir.'),
 ('Erişim koşullarını baştan belirtin','Kapalı otopark, eğimli alan, dar sokak veya yoldan çıkmış bir araç aynı koşulları sunmaz. Yükleme için ek işlem gerekip gerekmediği değerlendirilmelidir. Görüşme sırasında bu ayrıntıları paylaşmak, talebin eksik bilgiyle fiyatlandırılmasını önlemeye yardımcı olur.'),
 ('Teklifte hangi soruları sormalısınız?','Toplam ücrete yükleme ve teslimin dahil olup olmadığını, kurtarma işlemi gerekirse bunun nasıl değerlendirileceğini ve teslim adresi değişirse ücretin değişip değişmeyeceğini sorun. Ödeme yöntemini de baştan konuşun. Görüşmede netleşmemiş bir tutarı kesin fiyat kabul etmeyin.'),
 ('Diyarbakır için teklif isteyin','Konumunuzu, araç marka ve modelini, görünen sorunu ve teslim adresini hazırladıktan sonra Hizmet Oto Çekici ile iletişime geçebilirsiniz. Ücret ve ekip uygunluğu talebinize göre değerlendirilir. Bu yazıda sabit fiyat verilmemesinin nedeni, her taşımanın aynı koşullara sahip olmamasıdır.')]),
 ('en-yakin-cekici-secerken','ÇEKİCİ REHBERİ','Diyarbakır’da en yakın çekici nasıl seçilir?','Konum, ekipman uygunluğu ve net iletişim: çekici ararken birlikte değerlendirin.',[
 ('Yakınlık tek başına yeterli değildir','“Diyarbakır en yakın çekici” aramasında görünen sonuç, o anda boşta olan ve aracınızı taşıyabilecek ekibi kesin olarak göstermez. Haritadaki işletme noktası ile sahadaki aracın konumu da farklı olabilir. Bu yüzden ulaşım süresini telefonda teyit etmek gerekir.'),('İhtiyaca uygun aracı sorun','Otomobil, farklı ölçülerde bir araç veya erişimi zor yerde kalan bir araç için hazırlık aynı olmayabilir. Marka, model ve aracın durumunu paylaşın. “Aracım bu koşullarda alınabilir mi?” sorusu, yalnızca kaç dakikada gelineceğini sormak kadar önemlidir.'),('Konumu ve gidiş yönünü paylaşın','İlçe ve mahalle adı yanında harita konumu gönderin. Bölünmüş yolda bulunduğunuz tarafı ve hareket yönünü söyleyin. Sadece yakındaki bir işletmenin adını vermek yerine konumu tarif etmek, yanlış noktaya yönelme riskini azaltır.'),('Hizmet kapsamını netleştirin','Teklifin neleri kapsadığını ve aracın hangi adrese götürüleceğini konuşun. Tahmini varış süresi, trafik ve ekip durumuna bağlıdır. Çok kısa süre vaatlerinden hareketle kesin karar vermek yerine talebinizin anlaşıldığından emin olun.'),('Merkez ve çevre ilçeler','Kayapınar, Bağlar, Yenişehir ve Sur için talebinizi ilçe adıyla birlikte iletebilirsiniz. Çevre ilçelerden iletişime geçerken mesafeyi ve aracın bulunduğu alanı ayrıntılı anlatın. Hizmet Oto Çekici’ye telefon veya WhatsApp üzerinden ulaşarak uygunluğu görüşebilirsiniz.')]),
 ('cekici-icin-konum-nasil-paylasilir','PRATİK BİLGİLER','Çekici çağırırken konum ve araç bilgisi nasıl paylaşılır?','İlk görüşmede hazırlanacak kısa bilgi listesiyle talebinizi açıkça anlatın.',[
 ('Konum işaretini kontrol edin','Harita uygulamanızdaki konum işaretinin aracın bulunduğu yeri gösterdiğini kontrol edin. Konumu başka bir yerden gönderiyorsanız aracın gerçek noktasını işaretleyin. Telefonun konum tahmini özellikle kapalı alanlarda farklı bir yeri gösterebilir.'),('Adres ve yön bilgisi ekleyin','Konum bağlantısının yanında ilçe, mahalle, cadde veya yol adı yazın. Yol bölünmüşse gidiş yönünü belirtin. Otoparkta kalan araç için giriş kapısını, bulunduğu katı ve giriş yüksekliğine ilişkin bildiğiniz bilgileri paylaşın.'),('Aracın durumunu kısa anlatın','Marka ve model, aracın çalışıp çalışmadığı, tekerleklerin hareket durumu ve anahtarın mevcut olup olmadığı işe yarayan bilgilerdir. Teknik teşhis koymanız gerekmez. “Motor çalışıyor ama araç hareket etmiyor” gibi gözleme dayanan bir açıklama kullanabilirsiniz.'),('Teslim noktasını unutmayın','Çekiciye yalnızca nereden alınacağını değil, nereye götürüleceğini de söyleyin. Servise taşınacaksa servis adını, açık adresini ve teslim alacak kişinin iletişim bilgisini hazırlayın. Teslim adresi henüz belli değilse bunu görüşmede belirtin.'),('Örnek talep metni','“Merhaba, aracım Diyarbakır / [ilçe] / [mahalle] konumunda. Araç [marka-model], durumu [kısa açıklama]. [Servis veya adres] noktasına taşınmasını istiyorum. Uygunluğunuzu, tahmini ulaşım sürenizi ve toplam ücreti öğrenebilir miyim?” Bu metni kendi bilgilerinizle tamamlayıp WhatsApp’tan iletebilirsiniz.')]),
 ('oto-cekici-oto-kurtarma-farki','HİZMETLERİ TANIYIN','Oto çekici ile oto kurtarma arasındaki fark nedir?','Talebiniz standart taşıma mı, önce kurtarma işlemi mi gerektiriyor?',[
 ('Oto çekici ne için kullanılır?','Oto çekici, aracın bulunduğu noktadan başka bir adrese taşınması ihtiyacında devreye girer. Arızalı aracın servise ulaştırılması buna örnektir. Taşıma yöntemi ise araç türüne ve üreticinin taşıma talimatlarına göre değerlendirilmelidir; bütün araçlar için tek yöntem varsayılmaz.'),('Oto kurtarma hangi durumu anlatır?','Kurtarma, aracın taşımaya hazır olmayan bir konumdan alınması gerektiği durumları ifade eder. Yoldan çıkmış, sıkışmış veya erişimi zor bir noktada kalmış araç için önce bulunduğu pozisyonun değerlendirilmesi gerekir. Bu aşamada standart çekiciden farklı ekipman veya hazırlık gerekebilir.'),('İki hizmet aynı talepte birleşebilir','Bir araç önce bulunduğu alandan çıkarılıp ardından servise taşınabilir. Bu nedenle yalnızca “çekici istiyorum” demek yerine aracın durumunu anlatmak yararlıdır. Yükleme öncesindeki işlem ile sonraki taşımanın teklif kapsamını birlikte konuşun.'),('Fotoğraf ve konum neden istenir?','Alan genişliği, zemin, aracın duruşu ve çevresindeki engeller hizmetin değerlendirilmesine yardımcı olur. Fotoğrafı yalnızca güvenli bir konumdan paylaşın. Fotoğraf göndermek için araca yaklaşmanız gerekmiyorsa bulunduğunuz güvenli yerden durumu tarif edebilirsiniz.'),('Diyarbakır’da doğru talebi oluşturun','Oto kurtarma veya oto çekici ihtiyacınız için Hizmet Oto Çekici’yi arayarak konum ve araç bilgilerini paylaşabilirsiniz. Ekipman uygunluğu, taşıma adresi ve hizmet kapsamı görüşmede belirlenir. Aracın hasar durumuna dair teknik değerlendirme için yetkili servis görüşü ayrıca gerekebilir.')]),
 ('servise-arac-tasima-oncesi','ARAÇ TAŞIMA','Aracınızı servise taşıtmadan önce neleri hazırlamalısınız?','Alınıştan teslimata kadar telefonla netleştirebileceğiniz temel ayrıntılar.',[
 ('Servisin aracı kabul ettiğini teyit edin','Aracınızı götürmek istediğiniz servisi arayarak kabul durumunu ve çalışma saatini öğrenin. Özellikle mesai dışında bırakılacak bir araç için teslim prosedürünü baştan konuşun. Adresi yalnızca işletme adıyla değil, mümkünse konum bağlantısıyla kaydedin.'),('Anahtar ve iletişim bilgilerini hazırlayın','Aracın anahtarının kimde olduğu ve teslimde kimin aranacağı bilinmelidir. Aracı siz teslim edemeyecekseniz ilgili kişinin telefonunu paylaşın. Araç içindeki kişisel eşyaların durumu ve teslim sırasında kontrol edilecek ayrıntıları önceden planlayın.'),('Bulunduğu alanın erişimini anlatın','Kapalı otopark veya dar sokak gibi alanlarda aracın yanına ulaşmak standart yol kenarı yüklemesinden farklı olabilir. Otopark girişi, kat ve manevra alanı hakkında bildiklerinizi iletin. Aracın tekerlekleri hareket etmiyorsa bunu da ekleyin.'),('Araç türüne uygun taşıma','Otomatik, elektrikli veya farklı çekiş sistemine sahip araçlar için üreticinin taşıma talimatları önemlidir. Çekici talebinde marka, model ve araç tipini doğru paylaşın. Taşıma şekline kendiniz karar vermek yerine bilgileri hizmet sağlayıcı ve gerektiğinde servisle değerlendirin.'),('Ücret ve teslim noktası üzerinde anlaşın','Çıkış ve varış adresi, gerekli yükleme işlemi, tahmini ulaşım süresi ve toplam ücretin kapsamı görüşmede netleşmelidir. Adres değişikliği olacaksa hareket öncesinde haber verin. Diyarbakır’daki servise araç taşıma talebiniz için telefonla veya WhatsApp üzerinden iletişime geçebilirsiniz.')])]
def blogcards(limit=None):return '<div class="bloggrid">'+''.join(f'<a class="blogcard" href="/blog/{slug}/"><div class="blogtop"><span>{cat}</span>{icon("arrow")}</div><h3>{title}</h3><p>{desc}</p><span class="textlink">Yazıyı oku</span></a>' for slug,cat,title,desc,_ in ARTICLES[:limit])+'</div>'
faq=[('Diyarbakır’da hangi bölgelere hizmet veriyorsunuz?','Merkezde Kayapınar, Bağlar, Yenişehir ve Sur; ayrıca çevre ilçeler için çekici ve oto kurtarma taleplerini değerlendirebilirsiniz. Bulunduğunuz konuma göre ekip ve hizmet uygunluğunu telefonla teyit edin.'),('Çekici ne kadar sürede gelir?','Süre; ekibin konumu, uygunluğu, trafik ve yol koşullarına göre değişir. Tam konumunuzu paylaşarak görüşme sırasında tahmini ulaşım süresini öğrenebilirsiniz.'),('Çekici ücreti nasıl belirlenir?','Alınış ve teslim noktası, araç türü, yükleme koşulları ve gereken ekipman değerlendirilir. Talebinizi anlatıp toplam ücretin kapsamını hareket öncesinde netleştirin.'),('WhatsApp’tan konum gönderebilir miyim?','Evet. WhatsApp bağlantısını açarak konumunuzu, araç bilgilerini ve götürülmesini istediğiniz adresi paylaşabilirsiniz. Acil çekici taleplerinde doğrudan telefonla da iletişime geçebilirsiniz.')]
faqhtml='<div class="faqs">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in faq)+'</div>'
home=f'<section class="hero"><img class="hero-image" src="/assets/tow-hero.webp" width="1536" height="1024" alt="Yol üzerinde otomobil taşıyan sarı platformlu çekici; temsili görsel" fetchpriority="high"><div class="hero-shade"></div><div class="wrap hero-content"><span class="eyebrow light">DİYARBAKIR OTO ÇEKİCİ & OTO KURTARMA</span><h1>Yolda kaldığınızda,<br><em>bir telefon<br>yeter.</em></h1><p>Diyarbakır merkez ve çevre ilçelerinde çekici ihtiyacınız için yanınızdayız. Konumunuzu paylaşın, aracınızın taşınmasını planlayalım.</p>'+buttons()+'<div class="hero-note">Kayapınar · Bağlar · Yenişehir · Sur</div></div><span class="image-note">Temsili görsel</span></section><div class="infostrip"><div class="wrap stripgrid"><div><span>01</span><p><strong>Bizi arayın</strong>Aracınızın durumunu anlatın.</p></div><div><span>02</span><p><strong>Konum paylaşın</strong>Alınış ve teslim yerini belirtin.</p></div><div><span>03</span><p><strong>Birlikte planlayalım</strong>Uygunluk, süre ve ücreti öğrenin.</p></div></div></div><section class="section wrap"><div class="sectionhead"><div><span class="eyebrow">HİZMETLERİMİZ</span><h2>Aracınız için<br>doğru destek.</h2></div><p>Arıza, hareket edemeyen araç veya servise taşıma ihtiyacı. Durumunuzu anlatın, uygun hizmeti değerlendirelim.</p></div>'+servicecards()+'</section><section class="regions section"><div class="wrap region-layout"><div><span class="eyebrow">HİZMET BÖLGELERİMİZ</span><h2>Diyarbakır’ın<br>merkezinde.<br><span class="muted">Çevre ilçelerinde.</span></h2><p>En yakın çekici arayışınızda tam konumunuzu iletin. Ekip uygunluğu ve ulaşım süresini doğrudan öğrenin.</p><a class="textlink" href="/hizmet-bolgeleri/">Tüm hizmet bölgeleri '+icon('arrow')+'</a></div>'+regionlinks()+'</div></section><section class="section wrap"><div class="sectionhead"><div><span class="eyebrow">ÇEKİCİ REHBERİ</span><h2>Yola dair,<br>işinize yarayan bilgiler.</h2></div><a class="textlink" href="/blog/">Tüm yazılar '+icon('arrow')+'</a></div>'+blogcards(3)+'</section><section class="section faqsection"><div class="wrap faq-layout"><div><span class="eyebrow">MERAK EDİLENLER</span><h2>Aklınızdaki<br>sorular.</h2><p>Farklı bir sorunuz mu var?<br><a href="'+TEL+'">'+PHONE+'</a></p></div>'+faqhtml+'</div></section>'+cta()
page('','Diyarbakır Çekici & Oto Kurtarma | Hizmet Oto Çekici','Diyarbakır oto çekici ve oto kurtarma. Kayapınar, Bağlar, Yenişehir, Sur ve çevre ilçeler için arayın: 0536 587 66 73. WhatsApp ile konum paylaşın.',home)
page('hizmetler/','Diyarbakır Çekici ve Oto Kurtarma Hizmetleri','Diyarbakır oto çekici, oto kurtarma, acil çekici talebi ve servise araç taşıma. Araç ve konum bilginizle 0536 587 66 73 numarasından ulaşın.',intro('Hizmetler','Yolculuk durabilir.<br>Çözüm arayışınız durmasın.','İhtiyacınız olan hizmeti inceleyin; konum, araç durumu ve teslim noktasını bizimle paylaşın.','hizmetler/')+'<section class="wrap section">'+servicecards()+'</section>'+cta())
for slug,name,desc,lead,sections in SERVICES:
 path='hizmetler/'+slug+'/'
 content=''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)
 body=intro('Hizmetler','Diyarbakır '+name,lead,path)+'<div class="wrap article-layout section"><article class="prose">'+content+'<h2>Hizmet bölgeleri</h2><p>Kayapınar, Bağlar, Yenişehir ve Sur başta olmak üzere Diyarbakır merkez ve çevre ilçelerdeki talepleriniz için iletişime geçin. Konuma göre ekip uygunluğu teyit edilir.</p><a class="textlink" href="/hizmet-bolgeleri/">Bölgenizi inceleyin</a></article><aside class="contactbox"><span class="eyebrow">ÇEKİCİ TALEBİ</span><h2>Konumunuzla<br>başlayalım.</h2><p>'+desc+'</p>'+buttons()+'</aside></div>'+cta()
 page(path,'Diyarbakır '+name,desc+' İletişim: '+PHONE,body)
page('hizmet-bolgeleri/','Diyarbakır Çekici Hizmet Bölgeleri','Kayapınar, Bağlar, Yenişehir, Sur ve Diyarbakır çevre ilçeleri için çekici ve oto kurtarma talepleri. Konumunuzu paylaşın, uygunluğu öğrenin.',intro('Hizmet Bölgeleri','Merkezden çevre ilçelere<br>Diyarbakır çekici.','Bulunduğunuz ilçeyi seçin. Konum ve araç durumuna göre hizmet uygunluğunu birlikte değerlendirelim.','')+'<section class="wrap section">'+regionlinks()+'<div class="region-rest"><span class="eyebrow">ÇEVRE İLÇELER</span><h2>İlçe dışı yolda mı kaldınız?</h2><p>Çevre ilçeler ve bağlantı yolları için tam konumunuzu paylaşarak ekip uygunluğunu, tahmini ulaşım süresini ve taşıma teklifini öğrenin.</p><ul class="chips">'+''.join('<li>'+r+'</li>' for r in REGIONS)+'</ul><p class="smalltext">Listede ilçenizin bulunması, o anda yakınınızda boş bir çekici olduğu anlamına gelmez. Uygunluk telefon görüşmesinde teyit edilir.</p></div></section>'+cta())
for slug,name,lead,h,p in DISTRICTS:
 body=intro('Hizmet Bölgeleri',name+' çekici ve<br>oto kurtarma',lead,'')+'<div class="wrap article-layout section"><article class="prose"><h2>'+h+'</h2><p>'+p+'</p><h2>'+name+'’da çekici talebi için gerekli bilgiler</h2><ul><li>Mahalle, cadde veya sokak adı ve harita konumu</li><li>Aracın marka, modeli ve gözlemlediğiniz arıza durumu</li><li>Alınış alanının erişim koşulları</li><li>Servis veya diğer teslim adresi</li></ul><h2>En yakın çekici ve ulaşım süresi</h2><p>Aracın konumu ile ekibin uygunluğu birlikte değerlendirilir. Yakınlık tek başına kesin ulaşım süresi vermez; trafik ve yükleme hazırlığı da süreci etkiler. Konumunuzu ileterek güncel tahmini telefonda öğrenin.</p><h2>Taşıma ücretini önceden öğrenin</h2><p>Çıkış ve varış noktası, araç durumu ve gereken işlem ücretin kapsamını belirler. Toplam teklifte hangi işlemlerin bulunduğunu sorabilirsiniz.</p><a class="textlink" href="/blog/diyarbakir-cekici-fiyatlari-nelere-gore-belirlenir/">Çekici fiyatları rehberi</a></article><aside class="contactbox"><span class="eyebrow">'+name.upper()+' ÇEKİCİ</span><h2>Talebinizi<br>iletebilirsiniz.</h2><p>Arayın veya WhatsApp üzerinden konum paylaşın.</p>'+buttons()+'</aside></div>'+cta()
 page('hizmet-bolgeleri/'+slug+'-cekici/',name+' Çekici ve Oto Kurtarma',name+' oto çekici ve oto kurtarma talepleri için '+PHONE+'. Konumunuzu paylaşarak hizmet uygunluğunu ve taşıma teklifini öğrenin.',body)
page('kurumsal/','Kurumsal','Diyarbakır Hizmet Oto Çekici hakkında bilgi. Merkez ve çevre ilçelerde oto kurtarma ve araç taşıma talepleri için açık iletişim ve planlı süreç.',intro('Kurumsal','Yolda kalan araçlar için<br>açık iletişim, net plan.','Diyarbakır Hizmet Oto Çekici, oto çekici ve oto kurtarma ihtiyaçlarınızda ulaşabileceğiniz yerel hizmet işletmesidir.','')+'<section class="wrap section aboutgrid"><div class="aboutphoto"><img src="/assets/tow-hero.webp" alt="Otomobil taşıyan platformlu çekici, temsili görsel" width="1536" height="1024" loading="lazy"><span>Temsili görsel</span></div><article class="prose"><span class="eyebrow">BİZİ TANIYIN</span><h2>İlk adım,<br>ihtiyacınızı anlamak.</h2><p>Diyarbakır merkez ve çevre ilçelerinde oto çekici, oto kurtarma ve servise araç taşıma talepleriniz için telefon veya WhatsApp üzerinden bize ulaşabilirsiniz.</p><p>Her talepte aracın bulunduğu konum, hareket durumu ve teslim adresi birlikte ele alınır. Uygunluk, yapılacak işlem, tahmini ulaşım süresi ve ücret kapsamı görüşmede netleştirilir.</p><p>Kayapınar, Bağlar, Yenişehir ve Sur başta olmak üzere bölgenizden iletişime geçerek aracınıza uygun hizmeti sorabilirsiniz.</p><a class="textlink" href="/hizmetler/">Hizmetlerimizi inceleyin '+icon('arrow')+'</a></article></section>'+cta())
page('blog/','Diyarbakır Çekici Rehberi ve Blog','Diyarbakır çekici fiyatları, en yakın çekici seçimi, oto kurtarma ve servise araç taşıma hakkında özgün rehber yazıları.',intro('Blog','Yola dair<br>bilmeniz gerekenler.','Çekici çağırmadan önce sorulacak sorular, paylaşılacak bilgiler ve araç taşıma sürecine dair pratik rehberler.','')+'<section class="wrap section">'+blogcards()+'</section>'+cta())
for slug,cat,title,desc,sections in ARTICLES:
 body=intro('Blog',title,desc,'')+'<div class="wrap article-layout section"><article class="prose"><div class="article-meta">'+cat+' · '+NAME+'</div>'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)+'<div class="related"><h2>İlgili içerikler</h2>'+''.join(f'<a href="/blog/{s}/">{t} '+icon('arrow')+'</a>' for s,c,t,d,se in ARTICLES if s!=slug)+'</div></article><aside class="contactbox"><span class="eyebrow">DİYARBAKIR ÇEKİCİ</span><h2>Bir sorunuz<br>mu var?</h2><p>Konumunuzu ve araç durumunu paylaşın. Talebinizi birlikte değerlendirelim.</p>'+buttons()+'</aside></div>'
 page('blog/'+slug+'/',title,desc+' Diyarbakır Hizmet Oto Çekici rehberi.',body,article=True)
page('iletisim/','İletişim — 0536 587 66 73','Diyarbakır Hizmet Oto Çekici iletişim: 0536 587 66 73. Arama veya WhatsApp ile konumunuzu paylaşın, çekici ve oto kurtarma talebinizi iletin.',intro('İletişim','Yardım için<br>doğrudan ulaşın.','Diyarbakır merkez ve çevre ilçelerinde çekici talebiniz için bizi arayın veya WhatsApp üzerinden yazın.','')+f'<section class="wrap section contactgrid"><a class="contacttile" href="{TEL}">{icon("phone")}<span>TELEFON</span><h2>{PHONE}</h2><p>Uygunluk, ulaşım süresi ve fiyat için arayın.</p><strong>Aramayı başlat '+icon('arrow')+f'</strong></a><a class="contacttile whatsapp" href="{WA}" target="_blank" rel="noopener noreferrer">'+icon('chat')+'<span>WHATSAPP</span><h2>Konumunuzu paylaşın.</h2><p>Araç bilgilerini ve teslim adresini iletin.</p><strong>WhatsApp’ı aç '+icon('arrow')+'</strong></a><div class="contactlist"><h2>Görüşme öncesi kısa liste</h2><ol><li>Bulunduğunuz ilçe ve açık konum</li><li>Araç marka, model ve hareket durumu</li><li>Varsa erişim kısıtı veya otopark bilgisi</li><li>Götürülmesini istediğiniz adres</li></ol><p>Hizmet alanı: Diyarbakır merkez ve çevre ilçeler. Tam adresli bir ofis ziyareti yerine, araç konumunuz üzerinden hizmet talebi oluşturabilirsiniz.</p></div></section>')
page('gizlilik/','Gizlilik','Diyarbakır Hizmet Oto Çekici web sitesinde iletişim bağlantıları ve teknik veri işleme hakkında bilgilendirme.',intro('Gizlilik','Gizlilik hakkında','Web sitesini ve iletişim bağlantılarını kullanırken.','')+'<article class="wrap prose section"><h2>Bu web sitesindeki bilgiler</h2><p>Bu site üzerinde üyelik, ödeme veya kişisel bilgi toplamak için hazırlanmış bir iletişim formu bulunmaz. Siteye reklam izleme ya da ziyaretçi analiz kodu eklenmemiştir. Barındırma hizmeti, teknik işleyiş ve güvenlik için bağlantı kayıtları işleyebilir.</p><h2>Telefon ve WhatsApp bağlantıları</h2><p>Arama bağlantısı cihazınızın telefon uygulamasını; WhatsApp bağlantısı ilgili harici hizmeti açar. Bu hizmetlerde paylaştığınız bilgiler, hizmet sağlayıcının kendi koşulları ve gizlilik politikaları kapsamındadır. Konum paylaşımı otomatik yapılmaz; ne paylaşacağınıza siz karar verirsiniz.</p><h2>İletişim</h2><p>Bu siteyle ilgili sorularınızı <a href="'+TEL+'">'+PHONE+'</a> numarasına iletebilirsiniz.</p></article>')
page('404/','Sayfa Bulunamadı','Aradığınız sayfaya ulaşılamadı. Diyarbakır Hizmet Oto Çekici ana sayfasına dönün.',intro('Sayfa bulunamadı','Bu sayfa bulunamadı.','Ana sayfadan hizmetlerimize ulaşabilir veya bizi arayabilirsiniz.','')+'<section class="wrap section"><a class="btn yellow" href="/">Ana sayfaya dön</a></section>')
(OUT/'404.html').write_text((OUT/'404/index.html').read_text().replace('<meta name="theme-color"','<meta name="robots" content="noindex"><meta name="theme-color"'))
(OUT/'404/index.html').unlink();(OUT/'404').rmdir();PAGES.remove('404/')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+DOMAIN+'/'+p+'</loc></url>' for p in PAGES)+'</urlset>')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+DOMAIN+'/sitemap.xml\n')
(OUT/'.nojekyll').touch()
print('Generated',len(PAGES),'pages for',DOMAIN)
